variables:
  RENOVATE_ENDPOINT: $CI_API_V4_URL
  RENOVATE_PLATFORM: gitlab
  RENOVATE_AUTODISCOVER: "false"
  RENOVATE_REQUIRE_CONFIG: required
  RENOVATE_ONBOARDING: "true"
  RENOVATE_ONBOARDING_CONFIG: '{"$schema":"https://docs.renovatebot.com/renovate-schema.json","extends":["config:base",":combinePatchMinorReleases",":disableRateLimiting",":enableVulnerabilityAlertsWithLabel(Triage)",":ignoreUnstable",":maintainLockFilesWeekly",":pinAllExceptPeerDependencies",":rebaseStalePrs",":semanticCommits",":separateMultipleMajorReleases","npm:unpublishSafe","regexManagers:dockerfileVersions","replacements:all"],"dependencyDashboardAutoclose":true,"gitLabIgnoreApprovals":true,"platformAutomerge":true,"ignoreScripts":true,"rollbackPrs":true,"packageRules":[{"matchPackageNames":["aws-sdk","boto3","botocore"],"schedule":["after 1am on a Sunday"],"groupName":"aws-dependencies"},{"matchUpdateTypes":["minor","patch","pin","digest"],"automerge":true}],"regexManagers":[{"fileMatch":["(?:^|/)Dockerfile[^/]*$"],"matchStrings":["FROM\\s+(?:--platform=linux\\/[^\\s]+\\s+)?(?:\\${REGISTRY_PROXY-?})?(?<depName>[^:\\s]+?):(?<currentValue>[a-z0-9.-]+)(?:@(?<currentDigest>sha256:[a-f0-9]+))?(?:\\s|$)"],"datasourceTemplate":"docker","versioningTemplate":"docker"},{"fileMatch":["(?:^|/)(?:docker-)?compose[^/]*\\.ya?ml$"],"matchStrings":["image:\\s+(?:\\${REGISTRY_PROXY-?})?(?<depName>[^:]+?):(?<currentValue>[a-z0-9.-]+)(?:@(?<currentDigest>sha256:[a-f0-9]+))?(?:\\s|$)"],"datasourceTemplate":"docker","versioningTemplate":"docker"}],"npmrc":"@example:registry=https://gitlab.example/api/v4/projects/xxx/packages/npm/","registryAliases":{"$CI_REGISTRY":"registry.gitlab.example","${CI_REGISTRY}":"registry.gitlab.example","$CI_TEMPLATE_REGISTRY_HOST":"registry.gitlab.com","${CI_TEMPLATE_REGISTRY_HOST}":"registry.gitlab.com"}}'
  RENOVATE_OPTIMIZE_FOR_DISABLED: "true"
  RENOVATE_REPOSITORY_CACHE: enabled
  RENOVATE_IGNORE_PR_AUTHOR: "true"
  RENOVATE_EXTENDS: github>whitesource/merge-confidence:beta
  RENOVATE_LOG_FILE: renovate-log.ndjson
  RENOVATE_LOG_FILE_LEVEL: debug
  LOG_LEVEL: info
  # Job Stage settings
  ARTIFACT_DOWNLOAD_ATTEMPTS: 3
  GET_SOURCES_ATTEMPTS: 3
  RESTORE_CACHE_ATTEMPTS: 3

image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/renovate/renovate:35.38.0@sha256:7420ab486e11a727b7d99f0d00609e48bc3676f04c88e69983d3ed3d07ef1f88

default:
  # retry Jobs by default to try and cater for GitLab Runner flakiness regularly seen in pipelines
  retry:
    when:
      - always
    max: 2
  cache:
    key: ${RENOVATE_PROJECT_PATH}-renovate
    paths:
      - /tmp/renovate/cache/renovate/repository/
  artifacts:
    when: always
    expire_in: 1w
    paths:
      - ${RENOVATE_LOG_FILE}

renovate-self:
  stage: deploy
  variables:
    RENOVATE_TOKEN: ${SELF_RENOVATE_TOKEN}
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - renovate ${SELF_PATH} ${RENOVATE_EXTRA_FLAGS}

renovate:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - renovate ${RENOVATE_PROJECT_PATH} ${RENOVATE_EXTRA_FLAGS}
